num_workers: 4 # The number of workers to load the data
device: cpu # The device for the main pytorch computations
fail_dir: ""
move_if_fail: false

dataset:
  with_numpy_pc: true # Whether to add numpy_pc in the data_dict

slam:
  # Odometry config
  odometry: ???

  # Backend Config
  backend: ???

  # Loop Closure Config
  loop_closure:


defaults:
  - slam/odometry: icp_odometry
  - dataset: kitti
  - slam/odometry/local_map: kdtree
  - slam/odometry/initialization: CV
  - slam/odometry/alignment: point_to_plane_GN
  - slam/odometry/preprocessing: none
  - hydra/output: slam

